### ISSUE TITLE
`interval=0` does not work after the first time it gets reset

### ISSUE THREAD

**Issue by aanastasiou** [arkark/brainfuck-online-simulator#5]
Hi Takeshi

While using the interpreter, if you set the slider to some value and then reset it back to 0, the interpreter *does not* go back to "optimised mode".

To reproduce:
1. Navigate to the URL
2. Hit play (The program executes instantly and we see the final state)
3. Refresh
4. Move the "interval" slider to some value
5. Hit play (The program now executes at a lower speed as required)
6. Move interval back **to 0**
7. Hit play (The program now executes at 1ms delay)

At step 7, the program would have to run in "optimised mode" and just display the final state. It does not.

I think that [this](https://github.com/arkark/brainfuck-online-simulator/blob/master/src/js/BrainfuckInterpreter.js#L96) should really be `==`.

**Comment by arkark** [comment]
Thank you for your report!
I fixed it.
